version: "3.5"

services:
  database_master:
    build: 
      context: ./custom_mysql
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - 9090:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_DATABASE=db_prisma
      - MYSQL_PASSWORD=user
    networks:
      - mynetwork

  database_slave:
    image: mysql:8.0.30
    container_name: "database_slave"
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - 9091:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_DATABASE=db_prisma
      - MYSQL_PASSWORD=user
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysqldata_master:
  mysqldata_slave:
